version: 0.2

phases:
  build:
    commands:
      - echo Running aws s3 cp command...
      - aws s3 cp index.html s3://luit-aug-2024-silver-cicd-beta --acl public-read
      - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]  ; 
        then aws s3 cp index.html s3://luit-aug-2024-silver-cicd-prod/index.html --acl public-read; fi